### ISSUE TITLE
chromsome error  

### ISSUE THREAD

**Issue by zhaouu** [MicrosoftGenomics/FaST-LMM#14]
The new version add,' assert not np.isnan(chrom_list).any(), "chrom list should not contain NaN"', but when chromosome is a string, it can be wrong. So changes it to 'assert not pd.isnull(chrom_list).any()', maybe better?

**Comment by CarlKCarlK** [comment]
zhaouu,

Thanks for your report and thanks for using FaST-LMM.

I believe the code expects chromosomes to always be numeric.

- Carl



________________________________
