### ISSUE TITLE
python 3 support?

### ISSUE THREAD

**Issue by roamato** [MicrosoftGenomics/FaST-LMM#15]
Hi, are planning to support python 3? Do you have a sense of how demanding it would be to port over to v3?

**Comment by CarlKCarlK** [comment]
Roberto,

Thank you for you query.

We would love to make FaST-LMM support both Python 2 and Python 3, but it looks like it would be a big effort. Sadly, that means that we don't have any current plans to do the work. (On the bright side, I don't think it would be any harder than porting any other medium-sized Python project.)

Thanks for you interest in FaST-LMM,

Carl
http://research.microsoft.com/~carlk

**Comment by CarlKCarlK** [comment]
I’m happy to report that we’ve just released FaST-LMM for Python 3! Just “pip install fastlmm” or “pip install pysnptools”.
See https://pypi.org/project/fastlmm/ for details.

Everything from code & notebooks to API examples now runs on both Python 2.7+ and Python 3.7+.

Thanks for using FaST-LMM & PySnpTools.

Yours,
-              Carl

p.s. If you have ideas on how we can let interested folks know of the new release, please send us an email.

**Comment by clippert** [comment]
Awesome! Will have a  look.

**Comment by heckerma** [comment]
Way to go Carl!

Sent from my iPhone

On Jan 11, 2020, at 4:45 PM, Christoph Lippert <notifications@github.com> wrote:

﻿Awesome! Will have a look.
