### ISSUE TITLE
How to add Categorical variable to Correlation file ?

### ISSUE THREAD

**Issue by snashraf** [MicrosoftGenomics/FaST-LMM#17]
Hi Team,
we are trying to run a GWAS on a cancer datasets and we are trying to add some categorical Variable as Correlation datasets but it seems that its not working at all. 
Every time we are a getting below error 
   ****if not os.path.exists(item): raise Exception("Missing input file '{0}'".format(item))
Exception: Missing input file 'mini_pan_pheno.corr.bed'****

we tried using files (attached one ) and none of them works. 
1. mini_pan_pheno_corr_10.txt is an original file that we need to use as categorical and when we used directly ( without changing ) then its gets same error always. nevertheless when we removed all categorical columns then it works fine.
2.  mini_pan_pheno.corr_with_dummy_10.txt  ( we converted a categorical variable into dummies using method mentioned here https://www.packtpub.com/mapt/book/big-data-and-business-intelligence/9781783989065/1/ch01lvl1sec21/creating-dummies-for-categorical-variables but it didn't work as well. ( files is attached as well.
3. plink_10.txt ( we converted our original file mentioned in #1 using plink as mentioned here http://zzz.bwh.harvard.edu/plink/dataman.shtml by using command plink --bfile ../vcf/SNP.miss2ref.concise.min_maf --covar pheno.corr --write-covar --dummy-coding but it produced an enormous huge file but again we got same error this time as wel. ( file is attached as well plink_10.txt )
4. I am attaching an example of my pheno file as well and this file is mini_pan_phenotypic_10.txt
Can you guys please help me on this? 

[mini_pan_pheno_corr_10.txt](https://github.com/MicrosoftGenomics/FaST-LMM/files/876659/mini_pan_pheno_corr_10.txt)
[mini_pan_pheno.corr_with_dummy_10.txt](https://github.com/MicrosoftGenomics/FaST-LMM/files/876660/mini_pan_pheno.corr_with_dummy_10.txt)
[mini_pan_phenotypic_10.txt](https://github.com/MicrosoftGenomics/FaST-LMM/files/876661/mini_pan_phenotypic_10.txt)
[plink_10.txt](https://github.com/MicrosoftGenomics/FaST-LMM/files/876662/plink_10.txt)

**Comment by CarlKCarlK** [comment]
snashraf,

Thanks for your query. It is looking for file 'mini_pan_pheno.corr.bed' and not finding it. Can you share the function call you are making? e.g.  something like:

    # set up data
    bed_fn = "../../tests/datasets/synth/all"
    pheno_fn = "../../tests/datasets/synth/pheno_10_causals.txt"
    cov_fn = "../../tests/datasets/synth/cov.txt"
    # run gwas
    results_df = single_snp(bed_fn,  pheno_fn, covar=cov_fn, count_A1=True)

Thanks,
Carl

**Comment by snashraf** [comment]
I am already providing this mini_pan_pheno.corr files to why it is asking for mini_pan_pheno.corr.bed ? 
bed_fn = sys.argv[1]
pheno_fn = sys.argv[2]
cov_fn = sys.argv[3]
print bed_fn
print pheno_fn
#cov_fn = "../../tests/datasets/synth/cov.txt"

# run gwas
###################################################################
results_df = single_snp(bed_fn, pheno_fn, covar=cov_fn, count_A1=True)

**Comment by snashraf** [comment]
Hi Carl,

Yes you are correct as we running it like 
python myscript.py inputfile1 inputfile2 inputfile3

Yes, we are using mini_pan_pheno_corr_10.txt as covariate data set and we are getting error in that. If we remove all categorical variable ( Like cancer type, ethnicity etc ) in mini_pan_pheno_corr_10.txt then its working fine but having categorical variable is causing it to throw an error as mentioned above. 

thanks
Najeeb

**Comment by CarlKCarlK** [comment]
Najeeb,

Please tell us what your command-line actually is. I believe the problem likely with the way you are calling your script.

- Carl

**Comment by snashraf** [comment]
python Fast-LMM.py ../vcf/mini_pan.SNP.miss2ref.concise.min_maf mini_pan.pheno mini_pan_pheno.corr

I don't think that there is any issue with the way we are calling script above! It seems this is something to do with the format of covariate file !!

**Comment by CarlKCarlK** [comment]
Najeeb,

I'm happy we're both working at the same time :-)

On the command line, instead of 'mini_pan_pheno.corr' try giving the name of the file, e.g. one of these I suppose:

    mini_pan_pheno_corr_10.txt
    mini_pan_pheno.corr_with_dummy_10.txt
    mini_pan_phenotypic_10.txt
    plink_10.txt

Background: You don't need to give the suffix of 'bed' files (although you can) because they are really three files (*.bed,*bim,*.fam). But for all other types of input files (pheno and covariate), you must give the full file name including any suffixes.

**Comment by snashraf** [comment]
Thanks , actually it's around 11:40 PM here. I did try all three option but
it didn't work at all. It's saying same error every time .

**Comment by snashraf** [comment]
Did you have any example where you have used categorical variable as
correlation file ?

**Comment by CarlKCarlK** [comment]
Najeeb,

At the first level, this is a problem with input file names and not their contents. (At the second level, there could be content problems, but we must solve the first level first). To debug it, we must be methodical.

You said that your command line is:

      python Fast-LMM.py ../vcf/mini_pan.SNP.miss2ref.concise.min_maf mini_pan.pheno mini_pan_pheno.corr

And that it says:

     Exception: Missing input file 'mini_pan_pheno.corr.bed'

This is what we expect because you said you have no file named 'mini_pan_pheno.corr'. (Note the lack of a *.txt suffix and also the lack of '_10'

So, to debug this, please send me exact examples of your command lines. And the exact error message.
Also, please show me a "ls -las" (Linux) or 'dir' (Windows), to prove that all the files listed on your command line are really there.

- Carl

**Comment by snashraf** [comment]
Dear Carl,

I have given file "'mini_pan_pheno_corr_10.txt" here at Github because I just wanted to show you then lines of files and this then I changes the name of all files for sake of uploading it at Github. I know python and I already did these basic debugging as well. as I already mentioned above that "Yes, we are using mini_pan_pheno_corr_10.txt as covariate data set and we are getting error in that. If we remove all categorical variable ( Like cancer type, ethnicity etc ) in mini_pan_pheno_corr_10.txt then its working fine but having categorical variable is causing it to throw an error as mentioned above."

**Comment by CarlKCarlK** [comment]
The code for loading covariates first tries to load them from phenotype-type files and then, if there is an error, it tries to load them from SNP-type files. That code is:

    def _pheno_fixup(pheno_input, iid_if_none=None, missing ='NaN',count_A1=None):
    
        try:
            ret = Pheno(pheno_input, iid_if_none, missing=missing)
            ret.iid #doing this just to force file load
            return ret
        except:
            return _snps_fixup(pheno_input, iid_if_none=iid_if_none,count_A1=count_A1)

I'd guess you're getting some error on the phenotype-type file loading and then getting the final error message from the SNP-type file loading.

> Also, note that it is assuming that 'NaN' rather then '-9' marks missing data.

The first fix is to change your script to explicitly tell it how your want your input files loaded. Something like:

    from pysnptools.snpreader import Bed,Pheno
    bed_fn = sys.argv[1]
    pheno_fn = Pheno(sys.argv[2],missing='-9')
    cov_fn = Pheno(sys.argv[3],missing='-9')
    print bed_fn
    print pheno_fn
    #cov_fn = "../../tests/datasets/synth/cov.txt"
    #run gwas.
    results_df = single_snp(bed_fn, pheno_fn, covar=cov_fn, count_A1=True)

I think when you run this way, you'll still get an error, but the error message will be more useful.

Also, here is the documentation on the Pheno(...) file loader. It includes little examples of the format: http://microsoftgenomics.github.io/PySnpTools/#snpreader-pheno

- Carl
