### ISSUE TITLE
Error with the phenotype file

### ISSUE THREAD

**Issue by AD-Farl** [MicrosoftGenomics/FaST-LMM#18]
So I am just trying to identify the bed_fn and pheno_fn.

I put them in as below:
bed_fn = "/home/xx/xx3/bed_file"
pheno_fn = " /home/xx/xx3/bed_file_pheno.txt"

results_df = single_snp(bed_fn, pheno_fn, count_A1=True)

I don't have a co-variant file. The bed file is a bed file! and the pheno file complies with the alternative phenotype file format for plink (family id, indiv id, pheno without a header) but I get this response:

No such file or directory: ' /home/xx/xx3/bed_file_pheno.txt.fam'

Should the phenotype file be in a different layout???

Thanks

**Comment by CarlKCarlK** [comment]
AD-Farl,

Thanks much for your question and for using FaST-LMM. There is likely some about the format of your phenotype file that FaST-LMM doesn't like, but currently its message is very misleading. (I'll try to improve the message in the next version). In the meantime, here are two things to try:

1. I notice an extra space in your pheno_fn
pheno_fn = " /home/xx/xx3/bed_file_pheno.txt"
                    ^EXTRA SPACE
Try removing that. If that works, you're done. If not, try this:

2.
from pysnptools.snpreader import Pheno
bed_fn = "/home/xx/xx3/bed_file"
pheno = Pheno("/home/xx/xx3/bed_file_pheno.txt") #we specify the reader for the file explicitly to  get better error messages if there are problems with the format.
results_df = single_snp(bed_fn, pheno, count_A1=True)

Please let us know if this helps,
Yours,
Carl
