### ISSUE TITLE
Why limit the chomosome number between [0,26]?

### ISSUE THREAD

**Issue by xiekunwhy** [MicrosoftGenomics/FaST-LMM#20]
Hi,
I often get Error "Expected a Chromosome in the form of an integer from 0-26 in file" when using Linux binary version of Fast-LMM for non-human species, I wonder that if you can do some modify to accept extra chromosome ids or remove the limitation?

Best wishes!

**Comment by xiekunwhy** [comment]
And I don't think this limitation is necessary for Fast-LMM or any other softwares!

**Comment by bobd00** [comment]
Please confirm the version you are using. The help for the C++ version says:
    -maxChromosomeValue <int>
        PLINK format specified human chromosome numbers and are thus
        limited to 0-26 (0=missing, 1-23, x=23, y=24, xy=25, mt=26).
        Use -MaxChromosomeValue to specify a different limit for the
        maximum chromosome number FastLmm accepts.

**Comment by xiekunwhy** [comment]
Thank you, I found this option when I update to FastLmmC v2.07.20140723.
Thank you very much.
