### ISSUE TITLE
Mitochondrial DNA & Fastlmm

### ISSUE THREAD

**Issue by aar0n-aguh0b** [MicrosoftGenomics/FaST-LMM#22]
I am currently running into an issue when I try to run a script using mitochondrial DNA variants (PLINK file format) and phenotypic data collected from smooth muscle cells. When I try to rin my script that calls single_snp, I run into a concatenation issue with pandas. When single_snp.py calls pd.concat(frame_sequence), I get "ValueError: No objects to concatenate." I'm not sure what may cause this issue.

**Comment by CarlKCarlK** [comment]
Thanks for using FastLMM! It sounds like Pandas is complaining because there are no results to concatenate. I wonder if your data has only one chromosome (from FastLMM's point of view) and it is troubled when it tries to "leave_out_one_chrom". If this is the problem, you can avoid the problem by setting leave_out_one_chrom=false. The downside is that you'd be losing the benefits of leave_out_one_chrom which I believe is discussed in the documentation. Hope this help. - Carl

**Comment by aar0n-aguh0b** [comment]
Ah I see, that fixed the issue. Thank you. Would you be able to explain how intersect_apply functions? I am now receiving an error "AssertionError: no individuals remain after intersection, check that ids match in files" ; I am not sure which files I should be checking.

**Comment by CarlKCarlK** [comment]
You sent an email to the mailing list this morning, but somehow it hid your email address, so I'm replying here. The most likely cause I can think of for what you are seeing is that the iid's between your DNA data and your pheno data don't match. The program intersects iids and gets no individuals. The way to test of this is the problem, is to set your logging level to "DEBUG"
via
   import logging
   logging.basicConfig(level=logging.INFO)
and then re-run. You should see a message like: 
 "# of iids now 0". It it says "0" that means the iids aren't matching and you need to look at your files and make sure the iids match.
- Carl

**Comment by aar0n-aguh0b** [comment]
You were correct that the iids were not matching. Debugging shows the following:
```
DEBUG:root:iids do not match up, so intersecting the data over individuals
DEBUG:root:# of iids now 148
```
Where would these mismatches occur? I previously ran my script using autosomal snps, with identical .fam  and phenotype files, and it was successful.

**Comment by CarlKCarlK** [comment]
So, the "match up" message could just means that the iids are not in the same order between the *.fam file and the pheno file. The program reorders and intersects. The "# of iids" message means that after reordering (if needed) and intersecting (if needed) the number of iids that match between the *.fam file and the pheno file was 148. If this number seems right, then this is not the problem. If this number seems much too low, then you need to look at the input files and see why only 148 iids are common between them.

**Comment by aar0n-aguh0b** [comment]
Thank you for all your help! This is the rest of my debugging log. The number of iids is correct, so it may be another issue shown here?
```
DEBUG:root:iids do not match up, so intersecting the data over individuals
DEBUG:root:# of iids now 148
INFO:root:Setting GB_goal to 0.127303789973 GB
DEBUG:root:About to call cython matrixSubset
DEBUG:root:Back from cython matrixSubset
DEBUG:root:About to call cython matrixSubset
DEBUG:root:Back from cython matrixSubset
INFO:root:bed file is open mtDNA_qc.bed
DEBUG:root:starting 'lmm_cov.setSU_fromG()'
DEBUG:root:finished 'lmm_cov.setSU_fromG()'
DEBUG:root:search	0.0	[ 204.73650716]
DEBUG:root:search	0.099999	[ 207.00258228]
DEBUG:root:search	0.199998	[ 208.92430143]
DEBUG:root:search	0.299997	[ 210.7054843]
DEBUG:root:search	0.399996	[ 212.48049538]
DEBUG:root:search	0.499995	[ 214.36641945]
DEBUG:root:search	0.599994	[ 216.51025419]
DEBUG:root:search	0.699993	[ 219.15984605]
DEBUG:root:search	0.799992	[ 222.8648919]
DEBUG:root:search	0.899991	[ 229.43623131]
DEBUG:root:search	0.99999	[ 338.00903354]
DEBUG:root:search	0.038196219159	[ 205.6512604]
DEBUG:root:search	0.061802780841	[ 206.18887469]
DEBUG:root:search	0.023606561682	[ 205.30381671]
DEBUG:root:search	0.014589657477	[ 205.08456415]
DEBUG:root:search	0.009016904205	[ 204.94895637]
DEBUG:root:search	0.00557275327199	[ 204.8661136]
DEBUG:root:search	0.00344415093301	[ 204.81573131]
DEBUG:root:search	0.00212860233898	[ 204.78506639]
DEBUG:root:search	0.00131554859402	[ 204.76634507]
DEBUG:root:search	0.00081305374496	[ 204.75487683]
DEBUG:root:search	0.000502494849065	[ 204.7478318]
DEBUG:root:search	0.000310558895894	[ 204.74349501]
DEBUG:root:search	0.000191935953171	[ 204.74082155]
DEBUG:root:search	0.000118622942723	[ 204.73917192]
DEBUG:root:search	7.33130104483e-05	[ 204.73815343]
DEBUG:root:search	4.53099322746e-05	[ 204.73752436]
DEBUG:root:search	2.80030781737e-05	[ 204.73713573]
DEBUG:root:search	1.7306854101e-05	[ 204.7368956]
DEBUG:root:search	1.06962240727e-05	[ 204.73674722]
DEBUG:root:search	6.61063002823e-06	[ 204.73665552]
INFO:root:h2=0.0
```

**Comment by CarlKCarlK** [comment]
I'm looking at another issue that may be related. (perhaps caused by a change in Pandas). I won't be able to investigate more until this weekend.

**Comment by CarlKCarlK** [comment]
I haven't been able to reproduce your problem, but I have noticed something so that it may not matter. According to the debug output above your "h2" is 0. This means that LMM has decided not to use a mixed model and instead to do regular linear regression because it didn't find the similarity matrix useful. That means that instead of running single_snp, you can just run single_snp_linreg. e.g Instead of:
  results_dataframe = single_snp(test_snps=test_snps, pheno=pheno_fn,leave_out_one_chrom=False)
Run something like:
 results_dataframe = single_snp_linreg(test_snps=test_snps, pheno=pheno_fn)
Does this help?
