### ISSUE TITLE
leave_out_one_chrom = False causing trouble with IntRangeSet

### ISSUE THREAD

**Issue by MichaelBeyeler** [MicrosoftGenomics/FaST-LMM#23]
Hi!

So, FaST-LMM has been working just fine up until now.

But for some tests I now require it to calculate the relationship matrix from the entire set of SNPs, meaning that I have to turn the option mentioned in the title to OFF.

However, when I run **single_snp(variants_to_test, phenotypes, leave_out_one_chrom=False)**, the single_snp function runs up until the point where it creates the frame.

The line

`sid_index_range = IntRangeSet(frame['sid_index'])`

produces the error message:

> Don't know how to construct a IntRangeSet from '1821321'

Do you know what might be causing this?

Best

**Comment by CarlKCarlK** [comment]
I can repro this.  It seems like IntRangeSet isn't working with Pandas, any more. I try to look into it more this weekend.

**Comment by CarlKCarlK** [comment]
Michael, for a work around, please find file intrangeset.py (for me, it's at C:\Anaconda2\Lib\site-packages\pysnptools\util\intrangeset.py) and change line 1630 from:
    if isinstance(iterable,(int,long)):
to
     if isinstance(iterable,(int,long,np.int64)):
A better fix involves using the 'numbers' package and I'll work on checking that in, but this work around should help you now.
- Carl

**Comment by CarlKCarlK** [comment]
We've updated PySnpTools to fix this and updated FastLMM to depend on the new version of PySnpTools. Please "pip uninstall pysnptools" and then "pip install pysnptools" to update your version of PySnpTools.
