### ISSUE TITLE
PED SnpReader not working?

### ISSUE THREAD

**Issue by cizydorczyk** [MicrosoftGenomics/FaST-LMM#24]
Hello,

I am trying to run FaST-LMM single_snp() using PED/MAP files as input like so:

```
# Load FaST-LMM basic association test:
from fastlmm.association import single_snp
from pysnptools.snpreader import Ped

# Load snp data:
ped_file = "/home/conrad/Data/primary_project_3/gwas/H17_plink/biallelic_snps_full/biallelic_snps_full_w_pheno"

pheno_fn = "/home/conrad/Data/primary_project_3/gwas/H17_plink/biallelic_snps_full/biallelic_snps_full.pheno"

# Run basic association test:
results_df = single_snp(test_snps=Ped(ped_file), pheno=pheno_fn)
```
Unfortunately, I get the following error:

```
/home/conrad/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/conrad/anaconda2/lib/python2.7/site-packages/pysnptools/snpreader/bed.py:42: FutureWarning: 'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'
  warnings.warn("'count_A1' was not set. For now it will default to 'False', but in the future it will default to 'True'", FutureWarning)
Traceback (most recent call last):
  File "practice.py", line 26, in <module>
    results_df = single_snp(test_snps=Ped(ped_file), pheno=pheno_fn)
  File "/home/conrad/anaconda2/lib/python2.7/site-packages/fastlmm/association/single_snp.py", line 148, in single_snp
    pheno = _pheno_fixup(pheno, count_A1=count_A1).read()
  File "/home/conrad/anaconda2/lib/python2.7/site-packages/pysnptools/snpreader/snpreader.py", line 455, in read
    val = self._read(None, None, order, dtype, force_python_only, view_ok)
  File "/home/conrad/anaconda2/lib/python2.7/site-packages/pysnptools/snpreader/bed.py", line 213, in _read
    self._run_once()
  File "/home/conrad/anaconda2/lib/python2.7/site-packages/pysnptools/snpreader/bed.py", line 98, in _run_once
    self._row = SnpReader._read_fam(self.filename,remove_suffix="bed")
  File "/home/conrad/anaconda2/lib/python2.7/site-packages/pysnptools/snpreader/snpreader.py", line 658, in _read_fam
    iid = np.loadtxt(famfile, dtype = 'str',usecols=(0,1),comments=None)
  File "/home/conrad/.local/lib/python2.7/site-packages/numpy/lib/npyio.py", line 803, in loadtxt
    fh = iter(open(fname, 'U'))
IOError: [Errno 2] No such file or directory: '/home/conrad/Data/primary_project_3/gwas/H17_plink/biallelic_snps_full/biallelic_snps_full.pheno.fam'
```
Ignoring the deprecation warning, it seems as though snpreader is trying to use a .bed file, even though I am trying to use a .ped file as input, and calling the Ped() snpreader. My associated .map file is named the same as the .ped file (with the .map extension). Obviously, since I am not using a .fam file, it cannot find it. I am unsure why it is looking for a .fam file in the first place, however.

Note that when I check the type() of the ped_file object, it is reported as the correct class (snpreader ped).

Being new to FaST-LMM, I am wondering if this is an issue or whether I am overlooking something.

Any help is much appreciated.

Thank you,
Conrad Izydorczyk

**Comment by CarlKCarlK** [comment]
Conrad,

Thanks for your question and thanks for using FaST-LMM. From the great info that you’ve provided, it looks like the problem is with reading your Pheno file, not your Ped file.

(When the program gets an input as a file name, it tries to read it with all the file readers. When they all fail, it – unfortunately – only gives the error message from the last reader, which is the Bed reader. This causes confusion and I’m thinking about the best way to fix it. In the meantime …)

If you use an explicit Pheno() reader, you should get a much more useful error message about what the pheno reader doesn’t like in your file.

Yours,
Carl

**Comment by cizydorczyk** [comment]
Thank you for your response - I tried it with the Pheno() reader and indeed, found an issue in my phenotypes file. I fixed the issue and no longer get this error.

Best,
Conrad Izydorczyk
