### ISSUE TITLE
FaST-LMM-Select

### ISSUE THREAD

**Issue by Owen-haha** [MicrosoftGenomics/FaST-LMM#28]
Hi developer, 
I want to try FaST-LMM-Select to select the SNPs for genetic similarity estimation but I cannot find the tool. Can someone send me a link of it? I checked the C++ version of FaST-LMM but did not find it.
Thanks!

**Comment by CarlKCarlK** [comment]
I believe it is in the python 2 version.
This Github is the right place.
________________________________

**Comment by heckerma** [comment]
Owen, before you use FaST-LMM-Select, I want to be sure you are aware of its pitfalls of and of better alternatives.  Please see https://www.nature.com/articles/srep06874.
