### ISSUE TITLE
interaction model

### ISSUE THREAD

**Issue by WarrenDavidAnderson** [MicrosoftGenomics/FaST-LMM#29]
Greetings and thanks for providing this excellent software. I am seeking clarification regarding unexpected behavior of the single_snp function in implementing a LMM with an interaction term. According to the API documentation [http://microsoftgenomics.github.io/FaST-LMM/](url) SNP by covariate interactions can be implemented as follows:

**interact_with_snp – index of a covariate to perform an interaction test with. Allows for interaction testing (interact_with_snp x snp will be tested) default: None**

I have a covariate file with 39 columns, including the first two columns with subject IDs:

`awk '{print NF}' covmat.txt | sort -nu | tail -n 1
39

head -3 covmat.txt | cut -f1-4
GTEX-111CU-0003-SM-5DWTR	GTEX-111CU-0003-SM-5DWTR	 0.000000000	-0.018000000
GTEX-111FC-0001-SM-5DWSO	GTEX-111FC-0001-SM-5DWSO	 0.000000000	-0.015600000
GTEX-111VG-0004-SM-5DWSX	GTEX-111VG-0004-SM-5DWSX	 0.000000000	-0.019700000`

I would like to examine SNP by covariate interactions for the 37th covariate in the 39th column of the covariate file. When I run this code,

`results_df = single_snp(bed_fn,  pheno_fn, covar=cov_fn, count_A1=True, interact_with_snp=37, output_file_name="outint.txt")`

I get an error:

`assert 0 <= interact_with_snp and interact_with_snp < covar.shape[1]-1, "interact_with_snp is out of range"`

It looks to me that I need to enter `interact_with_snp=36` to test the interaction for the 37th covariate (39th column of covariate file). Could you please confirm/clarify/advise?
Thanks much, W

**Comment by CarlKCarlK** [comment]
Warren,

Thanks for using FastLMM!

Yes, if you have 37 covariates and you want to test the interaction with the last one, then interact_with_snp=36
Should work. This is because the family and iid columns don’t count and because we start counting covariates with “0”.


  *   Carl

**Comment by WarrenDavidAnderson** [comment]
Thanks, Carl. Much appreciated.

Best, Warren

________________________________

**Comment by WarrenDavidAnderson** [comment]
Hi Carl,

Could you please confirm that when I run fast lmm with an interaction terms, the columns PValue and SnpWeight indicate the nominal p-value and the regression coefficient (beta) for the snp x covariate interaction term.

Thanks much,

Warren


________________________________

**Comment by CarlKCarlK** [comment]
Warren,

I’m sorry I don’t know that option well. I believe that it was added by Christoph Lippert who is now at https://www.mdc-berlin.de/lippert.

You might also want to look at the source code: https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/fastlmm/association/single_snp.py. The part related to interaction seems relatively simple.



  *   Carl



________________________________

**Comment by heckerma** [comment]
Warren,

Not sure Christoph got back to you.  I believe the answer is yes, but to confirm, would need to see how you are calling the code.

Thanks,

David

**Comment by WarrenDavidAnderson** [comment]
Hi David,

Thanks for getting in touch. I have not heard from Christoph. I am calling the function as follows:


results_df = single_snp(bed_fn,  pheno_fn, covar=cov_fn, count_A1=True, interact_with_snp=17, output_file_name=outname)

Best,

Warren

________________________________

**Comment by clippert** [comment]
Hi Warren,

What David writes is correct. The regression weights as well as the standard errors correspond to the (multiplicative) interaction term between a SNP at the corresponding position and the variable that you provided as input for the interaction.

Cheers,
Christoph

**Comment by WarrenDavidAnderson** [comment]
Hi Christoph,

Many thanks for confirming that.

Best,

Warren

________________________________
