### ISSUE TITLE
Which is the effect allele of the fastLMM results?

### ISSUE THREAD

**Issue by Owen-haha** [MicrosoftGenomics/FaST-LMM#30]
When I check the fastLMM output, I cannot tell which allele is the effect allele of the results. Can anyone confirm either the allele 1 or allele 2 of Plink file is the effect allele? 
Thanks!

**Comment by Owen-haha** [comment]
Sorry I didn't make it clear.

I am using the C++ version (maybe relative older than the python version) with Bed file format as input. The question is I am not sure which allele (A1 or A2) dose the tool count as "0, 1, 2". 

According to your reply, it is likely that the tool counts the allele base on A2. Any quick way to check it? Is it a good idea to check the correlation direction, by calculating the Pearson correlation coefficient? But I am not sure what does the mixed-model do to the correlation direction. 

Thanks for the reply!

**Comment by CarlKCarlK** [comment]
Owen,

The C++ code probably encodes the PLINK way (i.e., counting A1’s) [It was only an accident that I did the other way for Python.] I’m cc’ing Bob Davidson who might know.


  *   Carl

________________________________

**Comment by CarlKCarlK** [comment]
I am currently in Australia. I get back early next week and I'll take a look at it then.

Sent from my Windows Phone
________________________________
From: Carl KADIE<mailto:carlk@msn.com>
Sent: ‎5/‎4/‎2018 9:04 AM
To: MicrosoftGenomics/FaST-LMM<mailto:reply@reply.github.com>; MicrosoftGenomics/FaST-LMM<mailto:FaST-LMM@noreply.github.com>
Cc: Comment<mailto:comment@noreply.github.com>; Bob Davidson<mailto:Bob.Davidson@microsoft.com>
Subject: RE: [MicrosoftGenomics/FaST-LMM] Which is the effect allele of the fastLMM results? (#30)

Owen,

The C++ code probably encodes the PLINK way (i.e., counting A1’s) [It was only an accident that I did the other way for Python.] I’m cc’ing Bob Davidson who might know.


  *   Carl

________________________________

**Comment by Owen-haha** [comment]
I just did a simple experiment by comparing the beta estimates between FaST-LMM and BOLT-LMM (which explicitly shows effective allele in the output), using the same phenotype (standardized) and genotype. The Pearson correlation coefficient of beta estimates is >0.99 for SNPs with MAF >0.1. **So the result can confirm that the minor allele (A1 in Plink format) is the effective allele.** 

But the scales of beta estimates are different: `[-0.06, 0.06]` for FaST-LMM and `[-0.2, 0.1]` for BOLT-LMM. As mentioned in the FaST-LMM manual, each SNP is standardized to have mean 0 and standard deviation one across all individuals. Thus the effect sizes are per-SD not per-allele. This is probably the reason why the effect size scales are different between two tools. **Am I right? Any suggestion to transform the per-SD effect to per-allele effect?** Because per-allele effect is easier to interpret.

**Comment by heckerma** [comment]
Hi Owen,

Sorry for the delay and thanks for the confirmation.

You could do the transformation with a tool that computes the standard deviation of each SNP.  Or, if you’re up for it, you could add an output column in the python code.

Best,
David

**Comment by michellekee** [comment]
Hi,

I'm using fastLmm (C++) version and I'm still wondering what the effect allele denoted by FastLmm is? This post doesn't really address the solution as I'm not sure which format of plink the original post was referring to (was it the A1,A2 and maf calculated from plink or was it compared to GWAS calculated from plink? If it is the latter, was  "--keep-allele-order" flag was written in the command for plink?) 

Or, does FastLmm takes the A1 and A2 denoted in the .gen file as A1 and A2 in the FastLmm output file? 

Hoping to hear from you soon!

Thank you!

Cheers,
Michelle

**Comment by bobd00** [comment]
Hi Michelle,
I am not sure about the .gen file but the effect allele should be the minor allele (A1)
The SNPs are translated/encoded as:
```
real unknownOrMissing = std::numeric_limits<real>::quiet_NaN();  // now used by SnpInfo
real homozygousPrimaryAllele = 0.0;                // Major Allele
real heterozygousAllele = 1.0;                     
real homozygousSecondaryAllele = 2.0;              // Minor Allele
```

If reading from a dosage file, then the translation is:
```
// Return the real representing the dosage
//  If we are using Dosage1 format, return the single value
//  If we are using Dosage2 format, either missing or (2 * probability of homozygousMminor) + (probability of heterozygous)
//

```
-bobd-
