### ISSUE TITLE
Trait with zero point estimate of SNP-heritability

### ISSUE THREAD

**Issue by Owen-haha** [MicrosoftGenomics/FaST-LMM#31]
Greetings and thanks for providing this excellent software!

For some quantitative traits, e.g. plasma metabolites, the point estimate of SNP-heritability could be zero. In these cases, the assumption of "all SNPs have small (non zero) effect" is no longer hold. But FaST-LMM can still conduct association testing and return some genome-wide significant results.

How can I interpret these results? Can FaST-LMM still be able to correct the population structure (no PCs adding as covariates)?

**Comment by heckerma** [comment]
Hi Owen,

Yes, LMMs typically can handle both population structure and family/cryptic relatedness without PCs as covariates.  If you have ascertainment bias, however, you may want to have a look at https://www.nature.com/articles/nmeth.3285.

As for your first comment, as George Box used to say, “all models are wrong, but some are useful”.  ☺

Best,
David

**Comment by Owen-haha** [comment]
Hi David,

Thanks for the quick rely! 

I read the paper you mentioned but my phenotypes are quantitative traits. 

I just learned that the LMMs will degenerate to simple linear regression when genetic variance equals to zero. For instance, in the equation (1) of Lippert et al., 2011 when genetic variance (sigma_g2) is zero, it looks like simple linear regression. 

Am I safe to use FaST-LMM when genetic variance is very small (not zero)? In these cases, the ratio of residual variance to genetic variance will be very huge, say > exp(10). I checked the FaST-LMM manual (C++ version), the default range of searching is from `-brentMinLogVal -5` to `–brentMaxLogVal 5`. Can you point me some literature for these extreme cases? 


BTW, when running the FaST-LMM, we can prepare GRM (`-simOut`) or spectral decomposition (`-eigenOut`) in advance. What is the difference? Can the spectral decomposition help to reduce the running time and/or memory?

**Comment by clippert** [comment]
> On 23. May 2018, at 08:47, Owen <notifications@github.com> wrote:
> 
> Hi David,
> 
> Thanks for the quick rely!
> 
> I read the paper you mentioned but my phenotypes are quantitative traits.
> 
> I just learned that the LMMs will degenerate to simple linear regression when genetic variance equals to zero. For instance, in the equation (1) of Lippert et al., 2011 when genetic variance (sigma_g2) is zero, it looks like simple linear regression.
> 
correct.
> Am I safe to use FaST-LMM when genetic variance is very small (not zero)? In these cases, the ratio of residual variance to genetic variance will be very huge, say > exp(10). I checked the FaST-LMM manual (C++ version), the default range of searching is from -brentMinLogVal -5 to –brentMaxLogVal 5. Can you point me some literature for these extreme cases?
> 
It should not be a problem if sigma_g2 is small. Sometimes (the ML/REML estimate of) sigma_g2 goes to 0 or very large values.   Usually this happens, if the likelihood-surface is relatively flat and non-peaked and only slightly larger in one of the extremes.

This is equivalent to an estimate of h^2 = sigma_g2 / (sigma_g2 + sigma_e2)  going to 0 or 1.

Examples are shown in Figure 1 of https://www.nature.com/articles/jhg201415
> BTW, when running the FaST-LMM, we can prepare GRM (-simOut) or spectral decomposition (-eigenOut) in advance. What is the difference? Can the spectral decomposition help to reduce the running time and/or memory?
> 
> 

The only difference is that the spectral composition will be loaded from disk instead of being computed before the analysis. Unless you have very large sample sizes in the tens of thousands, or are using a very large number of SNPs (>millions) to compute the GRM, this probably won’t change the runtime very much.
