### ISSUE TITLE
Feeding my own GSM

### ISSUE THREAD

**Issue by Michael-Beyeler** [MicrosoftGenomics/FaST-LMM#32]
Like the title suggests, I've been trying to feed FaST-LMM a GSM that was generated by a different algorithm. So far, what I've been doing is loading the GSM via the FaST-LMM-internal LMM object:

```Gsm = np.genfromtxt('../Raw_Data/freeze2.common.rel.mat', skip_header=True)
Gsm = Gsm[:, 2:207]
Gsm = LMM(K=Gsm)
```

Then, I use `Gsm.setSU_fromK()` in order to get the spectrally transformed form of that relationship matrix.

Now, so far I've just kind of been tinkering in the `single_snp.py` file, manually feeding the Gsm.U and Gsm.S to the FaST-LMM GWAS algorithm. However, I don't think that's how it's supposed to be, and also I'm not sure what to make of the `h2` and `mixing`.

Might I have been overlooking something, and is there maybe a very easy and straight-forward way to import custom GSMs to do GWAS with them on FaST-LMM?

**Comment by CarlKCarlK** [comment]
Michael,

Thanks for using FastLMM!

Single_snp has an input called K0 that I think does what you want. See http://microsoftgenomics.github.io/FaST-LMM/#single-snp

It takes as input something of type KernelReader. There are currently five subtypes of KernelReaders. The KernelData<http://microsoftgenomics.github.io/PySnpTools/#pysnptools.kernelreader.KernelData> subtype would likely be the easiest one for you to use.
KernelReaders are explained here: http://microsoftgenomics.github.io/PySnpTools/#module-pysnptools.kernelreader
(When a K0 is not specified, one is automatically constructed from the test_snps)


“Mixing” only applies if you give single_snp two kernels (K0 and K1).
“h2” is weight of K0 relative to the identity matrix. When it is not specified, single_snp file searchs for the best value. So, usually you would not specify it.


  *   Carl




________________________________

**Comment by Michael-Beyeler** [comment]
Awesome, this is working!

What I did, is create list variables `iids` and `pairwise_relationships`, then created a kernel from them, which I used as input for single_snp:


```
from pysnptools.kernelreader import KernelData

iids = [[line_1, line_1], [line_2, line_2], ...]
pairwise_relationships = [[1, 0.x, 0.x, ...], [0.x, 1, 0.x, ...], …, [0.x, …, 0.x, 1]]

my_kernel = KernelData(iid=iids, val=pairwise_relationships)

results_df = single_snp(VARIANTS_TO_TEST,
                            PHENOTYPE_DATA,
                            K0=my_kernel,
                            leave_out_one_chrom=False)

```

And this works fine. Thanks for your help!
