### ISSUE TITLE
single_snp default GSM calculation method

### ISSUE THREAD

**Issue by Michael-Beyeler** [MicrosoftGenomics/FaST-LMM#33]
Hello!

I have two questions concerning the GSM calculation method that is used in the single_snp function.

I have read that FaST-LMM offers two different approaches to estimate the GSM: a) from only a subset of variants provided, but b) also a method that calculates the GSM exactly, using all provided variants. So, I was wondering, which of the two approaches is used in the single_snp function?

My second question concerns the distance measuring method that is used to determine the optimal GSM. Is it ML or REML?

Best regards

**Comment by CarlKCarlK** [comment]
Michael,

Thanks for using Fast-LMM!

By default, single_snp uses all the variants. It uses REML.


  *   Carl


________________________________
