### ISSUE TITLE
Could fastLMM dealt with repeatable records model

### ISSUE THREAD

**Issue by Tinawang402** [MicrosoftGenomics/FaST-LMM#36]
Hi,
I will conduct GWAS on the mouse data.
In my case, each individual could have multiple records shown as follow:
            StrainID IID pheno
            129X1.SVJ 162 8.54605
            129X1.SVJ 426 8.13482
            129X1.SVJ 57 8.00406
             A.J 344 7.97635
             A.J 346 8.27816
            A.J 428 8.03877
My genotype data is based on Strain level.
From the instructions manual, I think fastLmm could dealt with such repeatable model.
Could I ask how to make fastlmm run under such model? Is there any manual for this?

In addition, there are two versions of fastlmm: python and C++.
Could both versions dealt with this? or just Python version?
Looking forwards to any of your possible reply! Thank you very much!

Best regards,
Tina.

**Comment by CarlKCarlK** [comment]
Tina,

Thanks for looking at Fast-LMM.

My collaborators all know more about biology that I. They may be able to jump in.

For me, could you explain strain levels a bit more for a computer scientist? (e.g. you said that an individual could have multiple records, but in your example, I don’t see an repeated IIDs.)

Yours,
Carl

Carl Kadie, Applied Researcher, Microsoft
http://research.microsoft.com/~carlk<https://na01.safelinks.protection.outlook.com/?url=http:%2F%2Fresearch.microsoft.com%2F~carlk&data=04%7C01%7Ccarlk%40microsoft.com%7C6a20727660984438f06f08d652fdfd9c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636787648220992986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C-1&sdata=MgUF%2FYmmCGNQJnJAC1g33IEHNL1Hm9WWqBDM77PKZ5I%3D&reserved=0>



________________________________

**Comment by clippert** [comment]
Hi,

The individuals with the same strain ID are genetically identical to each other.

You can try running fastlmm as is. The kinship matrix should reflect this automatically. There are some additional features that give you some computational savings, but will give the exact same result, just faster. Unless runtime is a severe limitation, I don't recommend using those, as they are not well documented.

--Christoph
Sent from my mobile.

**Comment by Tinawang402** [comment]
Hi Carl,

Thank you very much for your email!
And sorry for not making my question clear!
Here is my case:
StrainID == FID (family ID);
My genotype data is based on FID.
Go back to my data example:
                 FID        IID pheno
          129X1.SVJ 162 8.54605
          129X1.SVJ 426 8.13482
           129X1.SVJ 57 8.00406
For the FID "129X1.SVJ", three different IID 162, 426 and 57 have the same
genotypes; while records (pheno colum in the above example data) are
different.
I can't take average of the pheno across the IID as the power will be much
reduced.
I want to know, when I fit these data inside fastLMM, how fastLMM build up
similarity matrix?!
And could python and C++ versions of fastLMM do the same thing on my case?
If yes, I prefer to use C++ version of fastLMM, as I didn't use python too
much.
Looking forwards to your feedback!
Thanks again!

Best regards,
Tingting.

Christoph Lippert <notifications@github.com> 于2018年11月26日周一 上午5:14写道：

**Comment by CarlKCarlK** [comment]
Tingting,

As Christoph said, everything should just work C both versions. It will treat every mouse (and it’s phenotype) as an individual even if they are clones. It will know they are clones and do the right things because it will see that their genotypes are the same.


  *   Carl

________________________________

**Comment by Tinawang402** [comment]
Hi All,

Thank you very much for your email!
Your comments are quite helpful!
Now I am using fastLmm on my data.

Best regards,
Tingting.

Carl Kadie <notifications@github.com> 于2018年11月28日周三 上午6:18写道：
