### ISSUE TITLE
ImportError: cannot import name cross_validation in Linux OS

### ISSUE THREAD

**Issue by HongyanR** [MicrosoftGenomics/FaST-LMM#37]
from fastlmm.association import single_snp
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-4f92f738e5b1> in <module>()
----> 1 from fastlmm.association import single_snp

/mnt/c/Users/Hongyan/Desktop/FaST-LMM-master/FaST-LMM-master/fastlmm/association/__init__.py in <module>()
      4 from fastlmm.association.snp_set import snp_set
      5 from fastlmm.association.epistasis import epistasis
----> 6 from fastlmm.association.heritability_spatial_correction import heritability_spatial_correction
      7 from fastlmm.association.single_snp_all_plus_select import single_snp_all_plus_select
      8 from fastlmm.association.single_snp_linreg import single_snp_linreg

/mnt/c/Users/Hongyan/Desktop/FaST-LMM-master/FaST-LMM-master/fastlmm/association/heritability_spatial_correction.py in <module>()
     18 from pysnptools.standardizer import Unit
     19 import itertools
---> 20 from sklearn import cross_validation
     21 from scipy import stats
     22

ImportError: cannot import name cross_validation

**Comment by CarlKCarlK** [comment]
Greetings,

Thanks for your note and thanks for using FastLMM.

What version of Anaconda are you using?
Can you check what version of scikit learn it is including?
(My reason for asking: The error message says that a standard part of the scikit learn package is missing. That could mean that you are missing the whole scikit learn package, or it could mean that the scikit learn package has changed.)


  *   Carl

________________________________

**Comment by mb3152** [comment]
I am having this issue too. It is now:

from sklearn.model_selection import cross_validate

**Comment by CarlKCarlK** [comment]
Maxwell,

Thanks for running Fast-LMM and thanks for reporting this problem.

Can you tell me what version of Anaconda and Scikit learn you are using?

For example, here is how I find these version numbers:
C:\Users\carlk>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sklearn
>>> sklearn.__version__
'0.19.1'
>>>


Thanks,
Carl


________________________________

**Comment by mb3152** [comment]
‘0.20.1'

Max Bertolero, PhD
maxbertolero.org

**Comment by CarlKCarlK** [comment]
Max,

Thanks! What happens if you just try the ‘from sklearn.model_selection import cross_validate’ command on its own?

For example, I see:

c:\Users\Carl>python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn.model_selection import cross_validate
>>>


  *   Carl

________________________________

**Comment by mb3152** [comment]
Yes you can import cross_validate, but not cross_validation.

**Comment by CarlKCarlK** [comment]
Maxwell,

Good eye! It appears that in scikit-learn v0.20, the ‘cross_validation’ module has been replaced by ‘model_selection’.

I’ll try to update everything within the week, but for now, here is a work-around:

In any file that where you see a complaint about ‘cross_validation’, change every instance of ‘cross_validation’ to ‘model_selection’.

For example, HongyanR, reported seeing:

/mnt/c/Users/Hongyan/Desktop/FaST-LMM-master/FaST-LMM-master/fastlmm/association/heritability_spatial_correction.py in ()
18 from pysnptools.standardizer import Unit
19 import itertools
---> 20 from sklearn import cross_validation
21 from scipy import stats

So, he can edit /mnt/c/Users/Hongyan/Desktop/FaST-LMM-master/FaST-LMM-master/fastlmm/association/heritability_spatial_correction.py, with a text editor and change

From:
   heritability_spatial_correction.py(20):from sklearn import cross_validation
   heritability_spatial_correction.py(95):        m_fold = cross_validation.KFold(n=G_kernel.iid_count, n_folds=jackknife_count, shuffle=True, random_state=jackknife_seed%4294967295)

To:

from sklearn import model_selection
…
    m_fold = model_selection.KFold(n=G_kernel.iid_count, n_folds=jackknife_count, shuffle=True, random_state=jackknife_seed%4294967295)

Thanks again for you help in reporting and (I hope) solving this problem,
Carl


________________________________

**Comment by mb3152** [comment]
Yes, that is exactly what I ended up doing. There are three files in that directory that need to be changed in this manner. 

Thanks! 
Max Bertolero, PhD
maxbertolero.org

**Comment by CarlKCarlK** [comment]
Fixed in GitHub and PyPi
