### ISSUE TITLE
How is the SnpFractVarExpl calculated?

### ISSUE THREAD

**Issue by OmarAbouSaada** [MicrosoftGenomics/FaST-LMM#42]
In the python version of fastlmm, when you run single_snp() what does the SnpFractVarExpl column in the output represent for each SNP? I understand that it's the variance explained by each SNP but how is that calculated?

**Comment by CarlKCarlK** [comment]
Omar,

Thanks for using Fastlmm!

I’m not sure of the nice formula. The code that calculates the value is here:

https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/fastlmm/inference/lmm_cov.py


The most relevant code seems to be:
      beta = snpsKY / (snpsKsnps + penalty_)
      variance_explained_beta = (snpsKY * beta)

       r2 = YKY[np.newaxis,:] - variance_explained_beta

variance_beta = r2 / (N - 1.0) / snpsKsnps
fraction_variance_explained_beta = variance_explained_beta / YKY[np.newaxis,:] # variance explained by beta over total variance
dataframe['SnpFractVarExpl'] = np.sqrt(res['fraction_variance_explained_beta'][:,0])

I hope that helps,

Carl



________________________________

**Comment by OmarAbouSaada** [comment]
Thank you!

Just one more question you might be able to answer; I've gone through as many papers describing changes to Fastlmm as I could find and haven't identified one that describes this feature, though it might have slipped past me.
To give a citation for the use of the variance explained by each SNP should I simply cite the initial Fastlmm paper and link to this github?

**Comment by heckerma** [comment]
Hi Omar,

That works for me.

Best,
David
