### ISSUE TITLE
python and c version

### ISSUE THREAD

**Issue by JoonYuhl** [MicrosoftGenomics/FaST-LMM#43]
Hi,

I tested both python and c version of the fast lmm package and it seems like the c version exports a few more features than the python version. 

Is there a way to make the python version do this? 
( exporting the number of samples, etc)

Thank you

**Comment by CarlKCarlK** [comment]
Joon Yuhl,

Thanks for using Fast-Lmm!

Can you share some examples of the outputs you’re seeing and would like to see?

Thanks,
Carl

________________________________

**Comment by JoonYuhl** [comment]
Hi Carl,

Thank you for responding my email.
I have attached the head of the output for both python and c version.

If you look at the result of the c version, you can find N, Odds Ratio, and
other columns that are not included in the result of the python version.

My co-worker wants as much information as possible, but if there are
limited number of information that we can extract, I will make a list of
ones that we would really love to see.

Thank you.

Best,
Joon Yuhl Soh

**Comment by heckerma** [comment]
Hi Joon Yuhl Soh,

Will have a look, but wanted to let you know right away that Odds Ratio was included in error in the C++ version.  FaST-LMM is designed to handle continuous phenotypes, where Odds Ratio does not make sense.

Best,
David

**Comment by JoonYuhl** [comment]
Sounds good

Thank you for letting me know

**Comment by CarlKCarlK** [comment]
Joon Yuhl,

Thanks for the details. (I don’t think GitHub allows attachments so I don’t see those.)

As far as displaying the # of individuals (and # of SNPs). Here is how to do it in Python from a Bed-formatted file:


mport os

import numpy as np



from pysnptools.snpreader import Bed

snpreader = Bed("all.bed", count_A1=False)


print snpreader.iid_count

print snpreader.sid_count

500

5000

This example comes from the PySnpTools tutorial notebook. See
https://github.com/MicrosoftGenomics/PySnpTools/blob/master/doc/ipynb/tutorial.ipynb
and http://microsoftgenomics.github.io/PySnpTools/. These also show how to access data in other formats.

PySnpTools is a Pandas library we wrote for efficiently accessing SNP and related data. FastLMM uses it extensively.



  *   Carl


________________________________

**Comment by JoonYuhl** [comment]
Hi Carl,

Thank you for helping me with this

I'm currently using a bgen file to include the dosage information.

Would these commands also work for the bgen file?

Thank you.

Best,
Joon Yuhl Soh

**Comment by JoonYuhl** [comment]
I meant .dat file
I am sorry that I confused the file format

Best,
Joon

**Comment by CarlKCarlK** [comment]
Joon,

PySnpTools also includes a Dat reader. Here is an example from http://microsoftgenomics.github.io/PySnpTools/#snpreader-dat that gives the number of individuals and SNPs


>>> from pysnptools.snpreader import Dat

>>> data_on_disk = Dat('../examples/toydata.dat')

>>> print((data_on_disk.iid_count, data_on_disk.sid_count))
                                                                     (500, 10000)


  *   Carl


________________________________

**Comment by JoonYuhl** [comment]
Hi Carl,

That sounds great. I will try that.
I also finalized the features my coworker wanted and he was wondering if
there is a way to export q values, allele 1 and allele 2 in the result
file.

Again, thank you for your help.

Best,
Joon Yuhl Soh

**Comment by CarlKCarlK** [comment]
Joon,

The Dat reader doesn’t remember the two alleles. However, it looks like the information is available as the 2nd and 3rd columns of the text *.Dat file. You’d need to write a little python code to extract it.
Also, if you have a *.Map file, it is also text and also contains the same allele info the two last columns. The Map file is usually much smaller that the Dat.

For the QValue, I see this example of creating a QQ plot in https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/doc/ipynb/FaST-LMM.ipynb


# qq plot

from fastlmm.util.stats import plotp

plotp.qqplot(results_df["PValue"].values, xlim=[0,5], ylim=[0,5])

We didn’t document the ‘qqplot’ function, but when I look at the source code (https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/fastlmm/util/stats/plotp.py  )
I see this:

def qqplot(pvals, fileout = None, alphalevel = 0.05,legend=None,xlim=None,ylim=None,fixaxes=True,addlambda=True,minpval=1e-20,title=None,h1=None,figsize=[5,5],grid=True):
    '''
    performs a P-value QQ-plot in -log10(P-value) space
    -----------------------------------------------------------------------
    Args:
        pvals       P-values, for multiple methods this should be a list (each element will be flattened)
        fileout    if specified, the plot will be saved to the file (optional)
        alphalevel  significance level for the error bars (default 0.05)
                    if None: no error bars are plotted
        legend      legend string. For multiple methods this should be a list
        xlim        X-axis limits for the QQ-plot (unit: -log10)
        ylim        Y-axis limits for the QQ-plot (unit: -log10)
        fixaxes    Makes xlim=0, and ylim=max of the two ylimits, so that plot is square
        addlambda   Compute and add genomic control to the plot, bool
        title       plot title, string (default: empty)
        h1          figure handle (default None)
        figsize     size of the figure. (default: [5,5])
        grid        boolean: use a grid? (default: True)
    Returns:   fighandle, qnull, qemp
    -----------------------------------------------------------------------


Which says that it can return ‘qnull, qemp’ information.

Perhaps one of those (qemp?) is the qValue.



  *   Carl

**Comment by JoonYuhl** [comment]
Hi Carl,

Thank you very much for looking into this.
My coworker was trying to generate the allele information through the
package, but I agree that getting it from the input files definitely makes
sense.

I will also look into the qqplot details.

Thank you.

Best,
Joon Yuhl Soh

**Comment by michellekee** [comment]
Hi, 

Can the python version take .gen as a dosage file? Or is it strictly .dat?

Please advise.

Thank you so much!

Cheers,
Michelle

**Comment by CarlKCarlK** [comment]
Michelle,

It doesn’t know about the *.gen format. However, if you can write a little Python code to read *.gen and create a 2D Python array of numbers, then it is very easy to turn that array into a SnpData<http://microsoftgenomics.github.io/PySnpTools/#snpreader-snpdata> object, which Fastlmm can use.

If you can figure out how to read the *.gen format and create a single (floating point) number for each individual and each SNP, I’m happy to help with the rest. (You’ll also need to figure out how to extract a list of IDs for individuals and SNPs.)

Finally, this approach assumes your computer has enough memory that it can hold all the dosage data in memory.


  *   Carl


________________________________

**Comment by michellekee** [comment]
Hi Carl,

Thank you for your reply.

Could you please explain what the 1st-3rd columns (i.e: "null_0", "j", and "n")  are in the SnpData <http://microsoftgenomics.github.io/PySnpTools/#snpreader-snpdata> object? Is this similar to .beagle format <https://www.cog-genomics.org/plink2/formats#beagle>?

Sorry, we are new at this and would very much love to apply FastLmm to create our GWAS.

Thank you so much!

Cheers,
Michelle

**Comment by CarlKCarlK** [comment]
Hi, the columns are

SNP identifier (e.g. “null_0”), 1st Allele (e.g. “j”), 2nd Allele (e.g. “n”), one value per sample  (e.g. 2.0).
Note there is only one value per sample .


  *   Carl


________________________________

**Comment by michellekee** [comment]
Hi Carl,

Thank you so much for your reply! We are testing that at the moment. We also realised that C++ allows you to save the RRM as an output. Is this command available for the Python version as well?

Thank you so much!

Cheers,
Michelle

**Comment by CarlKCarlK** [comment]
Michelle,


  *   to save the RRM as an output. Is this command available for the Python version as well?
Kind of.

By default, the python single_snp function creates a kernel (which I think is the RRM) for each chromosome, by leaving the SNPs of the each chromosome out, one by one. So, it creates multiple kernels.

If you want to create just one, using all the data there is an example in http://microsoftgenomics.github.io/PySnpTools/#module-pysnptools.kernelreader:


>>> from pysnptools.standardizer import Unit
>>> snp_on_disk = Bed('../../tests/datasets/all_chr.maf0.001.N300',count_A1=False) # Specify some data on disk in Bed format
>>> kerneldata1 = snp_on_disk.read_kernel(Unit()) #Create an in-memory kernel from the snp data on disk.
>>> print('{0:.6f}'.format(kerneldata1.val[0,0]))
901.421836


This example uses a Bed reader, but it works with any other type of SnpReader, including the in-memory, SnpData.

The example shows how to print a single number from the kernel. To save the whole kernel to text, something like this would work

kerneldata1.val.savetxt("nameOfFile.txt")
   See https://docs.scipy.org/doc/numpy/reference/generated/numpy.savetxt.html


  *   Carl

**Comment by JoonYuhl** [comment]
Hi Carl,

I was trying the count_A1 option in fast lmm and have a question.

I tried both True and False for the count_A1 and got the same value for p
values and beta.
I was expecting to have opposite sign in the two result files, and was
wondering if this is normal for the package.

Did you remove the count_A1 option? or should I look in to my work to
figure out what is wrong?

Thank you.

Best,
Joon Yuhl Soh

**Comment by CarlKCarlK** [comment]
Joon Yuhl Soh,

I’m happy to say that I think I can answer this.

Short answer: When count_A1 changes,  pValues stay the same, but the sign of SnpWeight changes.

Details:

If I run the first example from the FaST-LMM notebook (https://github.com/MicrosoftGenomics/FaST-LMM/blob/master/doc/ipynb/FaST-LMM.ipynb), it looks this:


Ø  results_df = single_snp(bed_fn,  pheno_fn, covar=cov_fn, count_A1=True)

[cid:image002.png@01D4FEA0.C50D4270]

lambda=1.0078
Out[4]:

sid_index

SNP

Chr

GenDist

ChrPos

PValue

SnpWeight

SnpWeightSE

SnpFractVarExpl

Mixing

Nullh2

0

52

snp495_m0_.01m1_.04

5

4052

4052

2.990684e-23

-0.418653

0.040052

0.424521

0.0

0.451117

1

392

snp1422_m0_.49m1_.5

3

2392

2392

8.251922e-23

0.416495

0.040300

0.420587

0.0

0.279710

…


Now, if we change “count_A1=True” to “count_A1=False”, like so:


  *   results_df = single_snp(bed_fn,  pheno_fn, covar=cov_fn, count_A1=False)

the results change to:

[cid:image002.png@01D4FEA0.C50D4270]

lambda=1.0078
Out[5]:

sid_index

SNP

Chr

GenDist

ChrPos

PValue

SnpWeight

SnpWeightSE

SnpFractVarExpl

Mixing

Nullh2

0

52

snp495_m0_.01m1_.04

5

4052

4052

2.990684e-23

0.418653

0.040052

0.424521

0.0

0.451117

1

392

snp1422_m0_.49m1_.5

3

2392

2392

8.251920e-23

-0.416495

0.040300

0.420587

0.0

0.279711

…



The pValue doesn’t change because it is a measure of the confidence in the association between the SNP and the phenotype. The SnpWeight flips sign because we have changed which allele we’re asking about.

By way of analogy, if we used simple linear regression to look at data and try to take people’s height and predict their body mass, the result would likely have a positive feature weight and very small pValue. If we then tried to take  “negative height” and predict body mass, the sign on the feature weight would flip and the pValue would stay exactly the same.

Yours,
Carl

**Comment by JoonYuhl** [comment]
Hi Carl,

Thank you so much for the great answer.
If you don't mind, I wanted to ask just one more question.

I looked into what happened once more, and was thinking that this might be
due to the input data.

I am currently using a .dat file that has dosage information (0~2 range)
and maybe when we input the count_A1 option, the program doesn't know the
difference? Does this sound like a valid hypothesis?

Thank you.

Best,
Joon Yuhl Soh

**Comment by CarlKCarlK** [comment]
Ah, yes. The count_A1 option is only used when reading from a Bed file. So, for Dat it does nothing.


  *   Carl

________________________________

**Comment by JoonYuhl** [comment]
Thank you very much.
That was really helpful, I appreciate it.

Best,
Joon Yuhl Soh
