### ISSUE TITLE
fail to install 

### ISSUE THREAD

**Issue by JiayinLi-3724** [MicrosoftGenomics/FaST-LMM#44]
Hi,
I'm new to GWAS and I'm trying to install FaST-LMM on Windows. But I kept getting this error on both my PC and Lab Computer. I feel it seems like the issue of non-compatibility between Python 2 and Python 3.  But I couldn't install it using Python 2 either.
Could you guide me to fix it?
Thank you so much for your help! 
Best,
Jiayin  
 ----------------------------------------
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LIB-PA~2\AppData\Local\Temp\pip-install-1kl_ue28\fastlmm\setup.py", line 40
        print "removing", tmp_fn
                       ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("removing", tmp_fn)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\LIB-PA~2\AppData\Local\Temp\pip-install-1kl_ue28\fastlmm\

**Comment by CarlKCarlK** [comment]
Jiayin,

Thanks for using FaST-LMM!

As you suggest, the error message you're getting comes from running a Python 2 program in Python 3. FaST-LMM only works on Python 2. Can you try it with Python 2 and if that doesn't work, let us know the new error message?

Thanks,

  *   Carl



________________________________

**Comment by JiayinLi-3724** [comment]
Hi Carl,
Thank you so much for your help! I finally install FaST-LMM successfully, after solving lots of error messages. Can we expect FaST-LMM will work on Python 3 since Python 2 is going to retire? 

Best,
Jiayin

**Comment by CarlKCarlK** [comment]
Jiayin,

You’re welcome. Glad it is working for you.


  *   Can we expect FaST-LMM will work on Python 3

Coincidentally, I’m retiring from Microsoft this summer. I hope to port FaST-LMM to Python 3 as a hobby project.


  *   Carl

**Comment by CarlKCarlK** [comment]
I’m happy to report that we’ve just released FaST-LMM for Python 3! Just “pip install fastlmm” or “pip install pysnptools”.
See https://pypi.org/project/fastlmm/ for details.

Everything from code & notebooks to API examples now runs on both Python 2.7+ and Python 3.7+.

Thanks for using FaST-LMM & PySnpTools.

Yours,
-              Carl

p.s. If you have ideas on how we can let interested folks know of the new release, please send us an email.
