### ISSUE TITLE
`_regular_marginal_loglikelihood` is not defined

### ISSUE THREAD

**Issue by gaow** [MicrosoftGenomics/FaST-LMM#46]
I have this issue using `GLMM` class -- the problem is the following line of code:

https://github.com/MicrosoftGenomics/FaST-LMM/blob/495d4983b06f366e73fe8d6e2a12625673a81391/fastlmm/inference/glmm.py#L460

The error message:

```
  File "/opt/miniconda3/lib/python3.7/site-packages/fastlmm/inference/glmm.py", line 462, in marginal_loglikelihood
    margll = self._regular_marginal_loglikelihood()
AttributeError: 'GLMM_N3K1' object has no attribute '_regular_marginal_loglikelihood'
```

Then I realize I should use `LaplaceGLMM_N3K1`. But I guess it would still be nice to fix it here in `GLMM`.

**Comment by CarlKCarlK** [comment]
Gaow,

Thanks for using FaST-LMM!

Can you try the newer version of FaST-LMM at https://github.com/fastlmm/FaST-LMM and see you still see the problem? (The new version works with both Python 3 and 2)

If not, please tell me what you ran that shows the problem.
(I just run fastlmm\inference\tests\test.py and the line in question seemed to work for me.)

Yours,
Carl
Carl Kadie, Ph.D.
FaST-LMM & PySnpTools Team
(Microsoft Research, retired)

**Comment by gaow** [comment]
@CarlKCarlK Thank you for your prompt response. Sorry for not providing a test example earlier. Here is how the problem is reproduced.

## Install latest FaST-LMM

On Python 3.7,

```
pip install git+https://github.com/fastlmm/FaST-LMM -U
```

## Reproduce the issue above

```python
from numpy import dot, zeros
from numpy.random import RandomState
random = RandomState(0)
nsamples = 10
X = random.randn(nsamples, 2)
G = random.randn(nsamples, 100)
K = dot(G, G.T)
y = zeros(nsamples)
y[1:5] = 1
from fastlmm.inference.glmm import GLMM_N3K1
model = GLMM_N3K1()
model.setX(X)
model.setG(G)
model.setK(K)
model.sety(y)
model.optimize()
```

output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.7/site-packages/fastlmm/inference/glmm.py", line 348, in optimize
    bestCost = self._optimize(lowerBound, optSig02, optSig12, optSign2, optBeta)
  File "/opt/miniconda3/lib/python3.7/site-packages/fastlmm/inference/glmm.py", line 416, in _optimize
    (xfinal,aa,bb) = SP.optimize.fmin_tnc(func, x, fprime=grad, bounds=bounds, disp=0)
  File "/opt/miniconda3/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 275, in fmin_tnc
    res = _minimize_tnc(fun, x0, args, jac, bounds, callback=callback, **opts)
  File "/opt/miniconda3/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 409, in _minimize_tnc
    xtol, pgtol, rescale, callback)
  File "/opt/miniconda3/lib/python3.7/site-packages/scipy/optimize/tnc.py", line 371, in func_and_grad
    f = fun(x, *args)
  File "/opt/miniconda3/lib/python3.7/site-packages/fastlmm/inference/glmm.py", line 395, in func
    return -self.marginal_loglikelihood()
  File "/opt/miniconda3/lib/python3.7/site-packages/fastlmm/inference/glmm.py", line 462, in marginal_loglikelihood
    margll = self._regular_marginal_loglikelihood()
AttributeError: 'GLMM_N3K1' object has no attribute '_regular_marginal_loglikelihood'
```

**Comment by CarlKCarlK** [comment]
Gaow,

I don’t know this part of the code well, but when I look at fastlmm\inference\tests\test.py, I notice that the constructed classes are always
EPGLMM_N3K1 or LaplaceGLMM_N3K1. Moreoever, those two classes inherit (in the object-oriented code sense) like this:
class EPGLMM_N3K1(GLMM_N3K1, EPGLMM):
class LaplaceGLMM_N3K1(GLMM_N3K1, LaplaceGLMM)
So, my guess you need to construct one of those two and that that will define _regular_marginal_loglikelihood'.

Let me know if that works for you.


  *   Carl

p.s. I believe the GLMM code was contributed by Christian Widmer, but I don’t have contact info for him.

**Comment by gaow** [comment]
Indeed the other two GLMM classes are what I've been using. I thought GLMM code should be improved to avoid the confusion -- just eyeballing the GLMM code I see for example `_rmll_gradient` method also lacks definition. But I understand it might be challenging if the person contributes to the code is not available to fix / improve it. It's okay if you close this ticket.
