### ISSUE TITLE
LinAlgError: SVD did not converge

### ISSUE THREAD

**Issue by roamato** [MicrosoftGenomics/FaST-LMM#6]
single_snp* don't work and terminate with the error in the subject.
The same matrix works fine with the old C++ version of the code although it returns a warning saying that some eigenvalues are a tiny bit negative. Maybe the python and the old C++ version have different SVD routines with different default parameters (e.g. maximum number of iterations)?

**Comment by roamato** [comment]
It seems the problem was one of the covariates having missing data. The C++ was supporting this by mean imputation.

**Comment by heckerma** [comment]
Thanks Roberto.  We’ll put a fix on our todo list.  Best, David
