### ISSUE TITLE
Examples for output file and define phenotypes

### ISSUE THREAD

**Issue by mycecilia** [MicrosoftGenomics/FaST-LMM#7]
Hi,

Could anyone give me an example of output the results from single_snp()? Also an example of specifying a phenotype column when I have multiple columns of phenotypes in the PLINK alternative phenotype file.

Thank you.

ps: I tried to use the code as following:

import numpy as np
import pysnptools.util
from pysnptools.snpreader import Bed

from fastlmm.feature_selection.feature_selection_two_kernel import FeatureSelectionInSample
from pysnptools.util.pheno import loadOnePhen,loadPhen
from fastlmm.association import single_snp
# define file names

bed_fn = "PLINK"
bed2_fn = "PLINKpruned"
pheno_fn = "PLINKaltpheno.txt"
output_file_name="./fastlmm/chr1.txt"
# load data
###### 

snp_reader = Bed(bed_fn)
pruned_list=Bed(bed2_fn)
pheno = loadOnePhen(pheno_fn)
# intersect sample ids

snp_reader, pheno,bed2_fn = pysnptools.util.intersect_apply([snp_reader, pheno,pruned_list])
# read in snps
# partition snps on chr5 vs rest

test_chr = 5
G0 = pruned_list[:,pruned_list.pos[:,0] != test_chr].read(order='C').standardize()
test_snps = snp_reader[:,snp_reader.pos[:,0] == test_chr].read(order='C').standardize()

y = pheno['vals'][:,0]
y -= y.mean()
y /= y.std()
# invoke feature selection to learn which SNPs to use to build G1

print "running feature selection conditioned on background kernel"
# partition data into the first 50 SNPs on chr1 and all but chr1

select = FeatureSelectionInSample(max_log_k=7, n_folds=8, order_by_lmm=True, measure="ll", random_state=42)
best_k, feat_idx, best_mix, best_delta = select.run_select(G0.val, G0.val, y)    
# print results

print "best_k:", best_k
print "best_mix:", best_mix
print "best_delta:", best_delta
###### 
# use selected SNPs to build G1

print feat_idx
G1 = G0[:,feat_idx]

results_df = single_snp(test_snps, pheno, G0=G0, G1=G1, mixing=best_mix, h2=None，output_file_name=output_file_name) #linen 65

print 
print "results:"
print "#"*40
results_df.head()

This code gives me the error message:  
SyntaxError: Non-ASCII character '\xef' in file allselect.py on line 65, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by CarlKCarlK** [comment]
mycecilia,

Hi and thanks for you note.

I'm sorry that I can't offer straightforward advice. Here is are some ideas:

\xef is apparently a Unicode character that looks like an "i" with two dots. (http://www.codetable.net/hex/ef). I don't know what's doing here.

I looked at all my installed Python and on the Internet, but can't find a "allselect.py" file. Do you know what this is? If it is your file, then perhaps it accidently contains this strange character on line 65.

Have you been able to run the example in the notebook on the original sample files? You can download the sample input files from https://github.com/MicrosoftGenomics/FaST-LMM/tree/master/tests/datasets/synth

Yours,
Carl
