### ISSUE TITLE
Results Deflated

### ISSUE THREAD

**Issue by Sathish9** [MicrosoftGenomics/FaST-LMM#8]
I did the analysis (All), (All + Select) with PCs and getting deflated (~ 0.65) results. My case control dataset is imputed and contains individual from extended families. I tried various options i.e. transforming to liability scale and still getting deflated results.

Any suggestions would be helpful.

Regards,

Sathish

**Comment by jennilis** [comment]
Hard to say.

What’s your sample size?

What’s the proportion of case to control in your data set?

How many SNPs are non-imputed? Did you try the GWAS with only the non-imputed SNPs?

**Comment by heckerma** [comment]
Hi Sathish,

Assuming your case control data is skewed to include more cases, I would first preprocess the data with https://github.com/MicrosoftGenomics/LEAP.  And assuming you have a fair amount of non-imputed SNPs (say 100k), I would just use those for now.  Finally, I would focus on (All) only for starters, and make sure you are doing leave-out-one chromosome to avoid proximal contamination.

Best,

David

**Comment by Sathish9** [comment]
Hi,

What’s your sample size?
Answer: 475 related individuals with consanguinity


What’s the proportion of case to control in your data set?
Answer:  172 cases and 303 controls

How many SNPs are non-imputed? 
Answer: Around 450,000 un-imputed and 5160633 after imputation followed by filtering for info score > 0.8 and maf < 0.005 and conducting other SNP based QC.


Did you try the GWAS with only the non-imputed SNPs? 
Answer: Yes it is deflated.

I tried it with LEAP by transforming the phenotypes to liability scale and used ALL with LOOC.


Regards,

Sathish

**Comment by heckerma** [comment]
> I tried it with LEAP by transforming the phenotypes to liability scale and used ALL with LOOC.
And it is still substantially deflated?

Thanks,

David

**Comment by jennilis** [comment]
I’m not sure what the info score is, but to help debug the issue, you might try filtering on maf<0.05 to see if that changes anything.

**Comment by jennilis** [comment]
(and use only non-imputed SNPs)

From: Jennifer Listgarten
Sent: Sunday, September 20, 2015 8:01 PM
To: 'MicrosoftGenomics/FaST-LMM' <reply@reply.github.com>; MicrosoftGenomics/FaST-LMM <FaST-LMM@noreply.github.com>
Subject: RE: [FaST-LMM] Results Deflated (#8)

I’m not sure what the info score is, but to help debug the issue, you might try filtering on maf<0.05 to see if that changes anything.

**Comment by Sathish9** [comment]
Hi 

I cannot remember what was the deflation for un-imputed dataset. it must have been around 0.75. I will check again.

Info score is an imputation quality score and > 0.8 is high quality imputed SNPs. I used maf 0.005 since is more stringent than 0.05. However I notices there are SNPSs with high LD and I am assaying LOOC would have considered that.

I had similar deflated results using GCTA  with another dataset which had unrelated and related individuals. However I was asked to split the dataset into unrelated and related and conduct separate analysis. This gave me perfect results for unrelated and inflated results for related dataset.

I am not sure why this is happening with LMM especially with Family data? May be the distribution of relatedness is not homogenous in the relationship matrix.

Regards

Sathish

**Comment by jennilis** [comment]
> I used maf 0.005 since is more stringent than 0.05

Normally, to be sure they have data that behaves well, people keep only SNPs with maf>0.05. If one includes SNPs with maf>0.005, then one is including all of those and then some that are very rare, and then one is more open to having problems. Have I misunderstood either what you are doing or your definition of “stringent”?  If you haven’t already tried it, I would using only SNPs with maf>0.05 in the analysis (and only those which were not-imputed) to see if you still have a problem.
